// Generated by CoffeeScript 1.5.0
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = this.FeralHog) == null) {
    this.FeralHog = {};
  }

  FeralHog.ObservationModel = (function(_super) {

    __extends(ObservationModel, _super);

    function ObservationModel() {
      ObservationModel.__super__.constructor.apply(this, arguments);
    }

    ObservationModel.prototype.schemaName = "observation";

    return ObservationModel;

  })(StackMob.Model);

  FeralHog.ObservationsCollection = (function(_super) {

    __extends(ObservationsCollection, _super);

    function ObservationsCollection() {
      ObservationsCollection.__super__.constructor.apply(this, arguments);
    }

    ObservationsCollection.prototype.model = FeralHog.ObservationModel;

    return ObservationsCollection;

  })(StackMob.Collection);

  FeralHog.PhotoModel = (function(_super) {

    __extends(PhotoModel, _super);

    function PhotoModel() {
      PhotoModel.__super__.constructor.apply(this, arguments);
    }

    PhotoModel.prototype.schemaName = "photo";

    return PhotoModel;

  })(StackMob.Model);

  FeralHog.PhotossCollection = (function(_super) {

    __extends(PhotossCollection, _super);

    function PhotossCollection() {
      PhotossCollection.__super__.constructor.apply(this, arguments);
    }

    PhotossCollection.prototype.model = FeralHog.PhotoModel;

    return PhotossCollection;

  })(StackMob.Collection);

  FeralHog.ActionModel = (function(_super) {

    __extends(ActionModel, _super);

    function ActionModel() {
      ActionModel.__super__.constructor.apply(this, arguments);
    }

    ActionModel.prototype.schemaName = "action";

    return ActionModel;

  })(StackMob.Model);

  FeralHog.ActionsCollection = (function(_super) {

    __extends(ActionsCollection, _super);

    function ActionsCollection() {
      ActionsCollection.__super__.constructor.apply(this, arguments);
    }

    ActionsCollection.prototype.model = FeralHog.ActionModel;

    return ActionsCollection;

  })(StackMob.Collection);

}).call(this);
