// Generated by CoffeeScript 1.5.0
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = this.FeralHog) == null) {
    this.FeralHog = {};
  }

  FeralHog.Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.initialize = function() {
      FeralHog.observations.defaultView = "info";
      this.setObservationContainerClass();
      return Backbone.history.start();
    };

    Router.prototype.routes = {
      "": "clear",
      "observation/:id": "showObservation",
      "observation/:id/info": "showObservationInfo",
      "observation/:id/actions": "showObservationActions",
      "observation/:id/photos": "showObservationPhotos"
    };

    Router.prototype.clear = function(id) {
      this.destroyModals();
      if ((FeralHog.obsView != null) && (FeralHog.observations.selected != null)) {
        FeralHog.obsView.destroy();
        FeralHog.mapMarkers[FeralHog.observations.selected].setIcon('http://maps.google.com/mapfiles/ms/icons/red-dot.png');
        return FeralHog.observations.selected = null;
      }
    };

    Router.prototype.showObservationInfo = function(id) {
      return this.showObservation(id, "ObservationInfoView", "info");
    };

    Router.prototype.showObservationActions = function(id) {
      return this.showObservation(id, "ObservationActionsView", "actions");
    };

    Router.prototype.showObservationPhotos = function(id) {
      return this.showObservation(id, "ObservationPhotosView", "photos");
    };

    Router.prototype.showObservation = function(id, viewName, defaultView) {
      this.clear();
      FeralHog.observations.defaultView = defaultView;
      FeralHog.obsView = new FeralHog[viewName]({
        model: FeralHog.observations.get(id)
      });
      FeralHog.mapMarkers[id].setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png');
      return FeralHog.observations.selected = id;
    };

    Router.prototype.destroyModals = function() {
      $("#modalsContainer").html("");
      return $(".modal-backdrop").remove();
    };

    Router.prototype.setObservationContainerClass = function() {
      if ($(window).width() <= 1360) {
        $("#observationContainer").addClass("smallWindow");
      }
      return window.onresize = function(e) {
        if ($(window).width() <= 1360) {
          return $("#observationContainer").addClass("smallWindow");
        } else {
          return $("#observationContainer").removeClass("smallWindow");
        }
      };
    };

    return Router;

  })(Backbone.Router);

}).call(this);
